esphome:
  name: "hdmi-cec-test"
  on_boot:
    priority: -100
    then:
     - delay: 200ms
     - lambda: !lambda |-
         bool is_hw_uart = id(cec_uart)->get_hw_serial() != nullptr;
         ESP_LOGD("UART", "UART is HW_SERIAL=%d", is_hw_uart);
         id(cec).send(0x8, {0x90, 0x01});
         id(cec).send(0xf, {0x90, 0x00});
         // send 'feature abort' message to myself: will be accepted without creating a response message
         id(cec).send(0x1, id(cec).address(), {0x00, 0x90, 0x00});

external_components:
  - source:
      type: local
      path: components
    components: [hdmi_cec]

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  flash_size: 16MB

# Enable logging
logger:
  level: DEBUG

uart:
  id: cec_uart
  tx_pin:
    number: GPIO11  # has diode to cec pin, with kathode here on uart
#    number: GPIO03
  baud_rate: 1000

hdmi_cec:
  id: cec
  pin:   # to HDMI pin 13 (CEC), with HDMI pin 17 (DDC/CEC ground)
    number: GPIO12
    mode:
      input: true
      output: true
      pullup: true
      open_drain: true
  address: 0x5
  physical_address: 0x4000
  uart_id: cec_uart
  promiscuous_mode: true
